#!/usr/bin/env python3
"""
Corrige o banco Postgres (Neon) que ja foi populado por migrate_db.py.

Os dados foram migrados usando um schema criado em migrate_db.py com colunas
"id INTEGER PRIMARY KEY" simples — no Postgres isso NAO auto-incrementa
(diferente do SQLite). Sem esta correcao, qualquer INSERT novo feito pelo
app (criar cliente, iniciar importacao, etc.) sem passar um "id" explicito
falha com "null value in column id violates not-null constraint".

Roda uma vez so, contra o mesmo DATABASE_URL usado por migrate_db.py:

    set DATABASE_URL=postgresql://...
    python fix_identity_postgres.py

Idempotente: pode rodar de novo sem problema (ADD GENERATED e pulado se a
coluna ja for identity).
"""
import os
import sys

import psycopg2

TABELAS_COM_ID = [
    "clients", "imports", "import_columns", "dim_product", "dim_pdv",
    "dim_distribuidor", "source_mappings", "fact_sales", "fact_inventory",
    "fact_market", "dossies_html", "audit_logs", "price_data", "analyses",
    "opportunities", "strategies", "prompts", "ai_responses", "data_sources",
]


def main():
    url = os.environ.get("DATABASE_URL")
    if not url:
        print("[ERRO] DATABASE_URL nao configurada")
        sys.exit(1)

    conn = psycopg2.connect(url, sslmode="require")
    conn.autocommit = True
    cur = conn.cursor()

    for tabela in TABELAS_COM_ID:
        cur.execute(
            "SELECT is_identity FROM information_schema.columns "
            "WHERE table_schema='public' AND table_name=%s AND column_name='id'",
            (tabela,),
        )
        row = cur.fetchone()
        if row is None:
            print(f"  - {tabela}: tabela ou coluna 'id' nao encontrada, pulando")
            continue
        if row[0] == "YES":
            print(f"  = {tabela}: ja e identity, pulando")
            continue
        try:
            cur.execute(f"ALTER TABLE {tabela} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
            cur.execute(
                "SELECT setval(pg_get_serial_sequence(%s, 'id'), "
                "COALESCE((SELECT MAX(id) FROM " + tabela + "), 1))",
                (tabela,),
            )
            print(f"  ✓ {tabela}: identity adicionada, sequence ajustada")
        except Exception as e:
            print(f"  ⚠ {tabela}: {e}")

    cur.close()
    conn.close()
    print("\nConcluido.")


if __name__ == "__main__":
    main()
